name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validar sintaxis Python
        run: |
          python -m py_compile main.py

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Ejecutar pruebas
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generar artefactos
        run: |
          mkdir -p dist
          cp main.py dist/
          cp -r *.py dist/ || true
      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: release/
      - name: Simular despliegue
        run: |
          echo "Archivos copiados a release/"
          ls -l release/
