sonar:
  runs-on: ubuntu-latest
  needs: validate
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17 (required by SonarQube)
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
